### ISSUE TITLE
[Blog] Format des dates anglais => français

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2018#18]
Sur le blog le format des dates est en anglais, est-ce qu'il serait possible de le passer au format de date français ?

C.f capture : 
![image](https://user-images.githubusercontent.com/2543381/38268092-89b29ae4-377d-11e8-8b62-9bb16c344492.png)

Merci !

**Comment by davinkevin** [comment]
Awaiting PR validation: https://github.com/gdg-x/hoverboard/pull/439

**Comment by davinkevin** [comment]
Done :D
