### ISSUE TITLE
[Android>Ajouter a l'écran d'accueil] Titre (et logo?) a modifier

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2018#26]
Sur Android, il est parfois pratique d'ajouter un site en "favoris", sur Chrome -> Ajouter à l'écran d'accueil.

Lorsqu'on le fait, il y a actuellement : DevFest et le logo est grisé.

Serait il possible de modifier le titre en : DevFest Toulouse ?

Et de mettre le logo coloré, cela donnerai plus de peps que le logo tout gris, non ?

manifest.json a éditer je pense

![img_20180404_221332](https://user-images.githubusercontent.com/2543381/38332135-808ec78e-3855-11e8-9e35-902eb046c570.png)

**Comment by shprink** [comment]
C'est sur trello depuis un moment: https://trello.com/c/DXhErKij/35-site-pwa-logo-et-manifest
