### ISSUE TITLE
Changer le format du formulaire mailchimp

### ISSUE THREAD

**Issue by juliendelrio** [GDGToulouse/site-devfest-toulouse-2018#28]
La gestion de la liste a un peu changé pour qualifier qui s'est inscrit par le site et qui a été inscrit parce qu'il a participé à une précédente édition.

Le format actuel fait juste ouvrir un nouvel onglet avec le formulaire. Malheureusement, je n'ai pas la main assez finement sur ce formulaire pour mettre un champs caché avec le groupe coché par défaut pour dire que l'inscrit l'a fait par le site internet.
Il faudrait donc faire une intégration custom en suivant les recommandations qui sont ici : https://kb.mailchimp.com/fr/lists/signup-forms/automatically-add-subscribers-to-a-group-at-signup#hiddengroups

je pense que c'est une bonne issue pour @shprink 

Et je suis dispo sur slack s'il y a des questions.

**Comment by davinkevin** [comment]
Et cela ne sera pas plus simple de mettre le comportement officiel du projet hoverboard + les clouds functions (comme fait de base sur le projet) ? 

De ce fait, l'on pourrait faire ce que l'on veut des mails via [les clouds functions](https://github.com/GDGToulouse/site-devfest-toulouse-2018/blob/master/functions/src/mailchimp-subscribe.js)

**Comment by shprink** [comment]
Si

**Comment by davinkevin** [comment]
@shprink https://trello.com/c/beNqFnOt

Besoin d'informations complémentaires

**Comment by davinkevin** [comment]
Done in beac01e 👍
