### ISSUE TITLE
Add top navigation tab "Jobs"

### ISSUE THREAD

**Issue by juliendelrio** [GDGToulouse/site-devfest-toulouse-2018#58]
Like 2017, add a tab on top navigation called "Jobs".
This tab must send to jobs.devfesttoulouse.fr

**Comment by davinkevin** [comment]
Done in a branch, but: 
* jobs.devfesttoulouse.fr doesn't work in `https`, so we should not use this url but directly the taleez version
* the taleez page is stille branded with the 2017 version of DevFest Toulouse, is it normal ?

<img width="2270" alt="capture d ecran 2018-07-23 a 05 45 19" src="https://user-images.githubusercontent.com/1970922/43056736-32bdad38-8e3e-11e8-95f8-167e13d13ac1.png">

**Comment by davinkevin** [comment]
C'est prêt quand ?

**Comment by juliendelrio** [comment]
C'est prêt sur jobs.devfesttoulouse.fr
Merci
