### ISSUE TITLE
Mise à jour logo CNES

### ISSUE THREAD

**Issue by juliendelrio** [GDGToulouse/site-devfest-toulouse-2018#66]
Le CNES nous demande de mettre à jour leur logo en utilisant CNES_is_logo_2017_Logos carres.ai.
Merci

**Comment by davinkevin** [comment]
Done, avec celui ci => https://cdn.aderly.fr/uploads/2017/11/is_logo_cnes_logo_6-250x250.jpg (ne pouvant pas ouvrir le `.ai`)
