### ISSUE TITLE
Logo programmez magazine dans la section sponsor "Medias"

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2018#74]
Tout comme l'année dernière, le mgazine programmez nous offre de la visibilité pendant plusieurs mois sur leur magazine papiee et en ligne, ils vont nous envoyer encore cette année des magazines gratuitement également, du coup cela serait bien tout comme lan dernier d'ajouter leur logo dans la section sponsor "Medias" du site svp ! :-)

Merci !

**Comment by davinkevin** [comment]
Done ! 👍

![image](https://user-images.githubusercontent.com/1970922/45774304-e75d7c00-bc4c-11e8-85da-93dee7b274d2.png)
